language: node_js
node_js:
  - 6
install:
  - npm install 
  - npm run build
  - npm run fns:deps
after_success:
  - node_modules/.bin/firebase deploy --non-interactive --token "$FIREBASE_TOKEN" --project hnpwa-firebase-staging
  - curl https://hnpwa-firebase-staging.firebaseapp.com
  - node node_modules/lighthouse-ci/runlighthouse.js https://hnpwa-firebase-staging.firebaseapp.com
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_TOKEN"
