language: node_js
node_js:
  - 6
install:
  - npm install 
  - npm run build
  - npm run fns:deps
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./src/build/deploy_staging.sh; fi'
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "$FIREBASE_TOKEN"
  project: "hnpwa-firebase"
